### ISSUE TITLE
Server with --ssl not working.

### ISSUE THREAD

**Issue by flankerhqd** [mwrlabs/drozer#137]
I'm following these steps to enable SSL connection in drozer server and client. The client can connect to server successfully with SSL enabled, but "drozer console connect --ssl --accept-certificate" failed.

Steps to reproduce:

1. start drozer server with "drozer server start -ssl"
2. connect ssl-enabled client to server
3. add ca certificate produced by "drozer ssl --type ca create", following the instructions at http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate

4. run "drozer console connect -ssl"

if I don't run step 3, I will get 

```
~: drozer server start --ssl
Starting drozer Server, listening on 0.0.0.0:31415 (with SSL)
Using default SSL key material...
2014-11-12 22:33:01,359 - drozer.server.protocols.drozerp.droidhg - INFO - accepted connection from xxxxxx

~# drozer console connect --ssl
There was a problem connecting to the drozer Server.

Things to check:

 - is the drozer Server running?
 - have you set up appropriate adb port forwards?
 - have you specified the correct hostname and port with --server?
 - is the server protected with SSL (add an --ssl switch)?
 - is the agent protected with a password (add a --password switch)?

Debug Information:
[Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```
If I add the certificate produced by drozer to CA certificates, i.e. I ran step3
The following error produces:
```
~: drozer server start --ssl

Starting drozer Server, listening on 0.0.0.0:31415 (with SSL)
Using default SSL key material...
[('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]

```

**Comment by JosephRedfern** [comment]
Only 5 months late... but I've just had a look at this - there seem to be two separate issues. 

For the first issue:

I believe that the `SSL3_GET_SERVER_CERTIFICATE: certificate verify failed` error you're encountering is due to the [embedded CA] (https://github.com/mwrlabs/drozer/blob/491ccea93cd0a94c4ecd3d9b114f45e3719c5632/src/drozer/ssl/embedded_ca/drozer-ca.crt) and [embedded server cert](https://github.com/mwrlabs/drozer/blob/491ccea93cd0a94c4ecd3d9b114f45e3719c5632/src/drozer/ssl/embedded_ca/drozer-server.crt) having expired. This can be verified by running:

    ➜  embedded_ca git:(develop) ✗ openssl x509 -enddate -noout -in drozer-ca.crt    
    notAfter=Jul 17 08:42:31 2014 GMT

    ➜  embedded_ca git:(develop) ✗ openssl x509 -enddate -noout -in drozer-server.crt 
    notAfter=Jul 17 08:43:59 2014 GMT`

New default CAs and Server Certs will need to be generated and added to drozer for a permanent fix.

I suppose this also raises the question of why the agent agreed to connect to the server when the server was presenting an expired certificate - my guess is that it shouldn't be doing.

**Comment by JosephRedfern** [comment]
Now, for the issue you're running into after creating your own CA:

The command `drozer ssl --type ca create` will, as you say, generate a new CA. However, you also need to generate a keypair that has been signed by the new CA - creating a new CA alone is not enough.

By default, drozer will look for drozer-server.crt and drozer-server.key in the same location as the CA (which will be whatever folder you ran the `drozer ssl --type ca create` command in). To generate these files, you need to run `drozer ssl --type keypair create --subject "drozer-server"`.

You can specify a name other than `"drozer-server"` if you wish - if you choose to do this, you'll need to pass in the path to the .key file and .crt file when running `drozer server start --ssl` - for instance: `drozer server start --ssl /path/to/keyfile.key /path/to/crtfile.crt`.
