### ISSUE TITLE
Win7: Error Compiling Java Sources

### ISSUE THREAD

**Issue by darkknightjm** [mwrlabs/drozer#145]
Hi,
So I receive the following on Windows 7 -

drozer Console (v2.3.4)
dz> run app.package.manifest <some.app>
C:\Program Files\Java\jdk1.7.0_75\bin\javac.exe -cp C:\drozer\lib\drozer\lib\android.jar XmlAssetReader.java
javac: invalid flag: Files\Java\jdk1.7.0_75\bin\javac.exe
Usage: javac <options> <source files>
use -help for a list of possible options
Error whilst compiling the Java sources.
dz>

**Comment by wlc520123** [comment]
This occurs to me. 
I thougt the reason is that the installation path of JDK consists of a blank.
After my reinstall the JDK, the error is 

could not find javac

then I write the .drozer_config:
[executables]
java = C:\Java\jdk1.8.0_31\bin
javac=C:\Java\jdk1.8.0_31\bin\javac.exe

now, the error changes to:

c:\java\jdk1.8.0_31\javac.exe -cp c:\drozer\lib\drozer\lib\android.jar ByteStreamReader.java
c:\drozer\lib\drozer\lib\dx.bat --dex --output a2688a291cf591a2e088ff3adc958254.apk ByteStreamReader.class

trouble processing:
bad class file magic (cafebabe) or version (0034.0000)
...while parsing ByteStreamReader.class
...while processing ByteStreamReader.class
1 warning
no classifiles specified
drozer could not find or compile a required extension library.

**Comment by darkknightjm** [comment]
I tried installing on Ubuntu 14.04 and I got "drozer could not find or compile a required extension library". And aapt has the required permissions etc....

**Comment by wlc520123** [comment]
I has kown why.
In the wiki, I find:

https://github.com/mwrlabs/drozer/wiki/Running-on-the-edge

To compile Java sources for Android, you will need jdk6 installed and configured as the default version for  javac . If you use jdk7, the generated class files will not be compatible with the Android  dx  tool.

Therefore, I installed a JDK6, and in the .drozer_config file wirte:
[executables]
java = C:\Java\jdk1.6.0_24\bin
javac=C:\Java\jdk1.6.0_24\bin\javac.exe

problem done!

**Comment by darkknightjm** [comment]
Mind posting your config? Environment variables etc?

**Comment by metall0id** [comment]
I am coming into this quite late - sorry about that. Has everyone fixed their drozer's and things up and running?

@wlc520123 You are correct: drozer requires Java 1.6 to create compatible byte-code for Android

We recommend using drozer on Linux as it is the platform that we use to develop it and test on

**Comment by arunsunkumar** [comment]
Hi All,

I am facing the below issue:

dz> run app.package.manifest org.owasp.goatdroid.herdfinancial
C:\Program Files\Java\jdk1.6.0_45\bin\javac.exe -cp C:\Program Files\drozer\lib\drozer\lib\android.jar XmlAssetReader.java
javac: invalid flag: Files\Java\jdk1.6.0_45\bin\javac.exe


Kindly do the needfull.....

**Comment by SSantos62** [comment]
I have windows 10 and am getting the following error:

drozer console connect
Could not find java. Please ensure that it is installed and on your PATH.

If this error persists, specify the path in the ~/.drozer_config file:

    [executables]
    java = C:\path\to\java
[Errno 10054] An existing connection was forcibly closed by the remote host

I have created the .drozer_config.py file

Please does anyone know if drozer works on windows 10?

**Comment by truedelguyin** [comment]
any success in running drozer on windows10, its been 2 days now and I have tried all the mentioned configuration and its still giving me the same issue, path not found for java.
Let me know if anyone was able to run drozer on windows 10 with jdk 1.6

**Comment by Rude-superman** [comment]
Ensure both your path to java and drozer have no blanks.
problems done
