### ISSUE TITLE
drozer could not find or compile a required extension library - on mac OS X -10.9.5

### ISSUE THREAD

**Issue by nsanjeev16** [mwrlabs/drozer#147]
While running scanner.provider.* commands, it is throwing following error. 
I've installed 2.3.4 version - (https://www.mwrinfosecurity.com/system/assets/873/original/drozer-2.3.4.tar.gz)

dz> run scanner.provider.finduris -a package_name
Scanning package_name
drozer could not find or compile a required extension library.

**Comment by dbradberry** [comment]
Hi, sorry for the delay in replying.

There was an issue in some of the drozer 2.3.4 packages, which didn't include some pre-compiled apks. The easiest solution is to install from the re-issued package:

https://www.mwrinfosecurity.com/system/assets/933/original/drozer-2.3.4.tar.gz

Otherwise, you would need to install JDK6 and the Android SDK and make sure that drozer can find them on your PATH.
