### ISSUE TITLE
Try drozer exploit addjavascriptinterface example, but occurs error

### ISSUE THREAD

**Issue by magicislab** [mwrlabs/drozer#150]
HI, I try to run the drozer exploitation - addjavascriptinterface example, but it occurs following errors : 
![screen shot 2015-04-19 at 10 03 13 pm](https://cloud.githubusercontent.com/assets/10672049/7219710/ea033846-e6df-11e4-9f92-b681af190876.png)
Hope anyone could help me. Thanks a lot!

**Comment by JosephRedfern** [comment]
Hi Magicislab,

I believe that this is being caused by the bug described [here](https://github.com/mwrlabs/drozer/issues/143#issuecomment-69778652) - the .egg drozer package is missing the OSX aapt binary for some reason, and aapt is required during the agent repackaging process. 

Can you try copying aapt-osx (available here: https://github.com/mwrlabs/drozer/blob/master/src/drozer/lib/aapt-osx) to the libs folder of your drozer install? On OSX, this would normally be at `/usr/local/lib/python2.7/site-packages/drozer-2.3.3-py2.7.egg/drozer/lib/`. Make sure it's named "aapt-osx", as drozer looks for that name specifically under OSX.

Thanks,
Joe

**Comment by magicislab** [comment]
Hi, Joseph. 
Acutally, I already add the appt-osx in the drozer folder. But it seems to come up with same error. 
![screen shot 2015-04-20 at 8 50 38 am](https://cloud.githubusercontent.com/assets/10672049/7222160/83671ade-e73a-11e4-8615-10a96b7548aa.png)

**Comment by HenryHoggard** [comment]
Hi Magiclab, if you are still having this issue, can you please build drozer from the develop branch and retry.

Thanks

**Comment by metall0id** [comment]
Hopefully this is fixed in 13f8d76397a66f49ed4e831acc026ab5b7b27530

**Comment by amarekano** [comment]
Hi @magicislab, please follow Henry's advice on building the develop branch and reopen this issue if you're still having trouble getting it working.
