### ISSUE TITLE
Crashes when run scanner

### ISSUE THREAD

**Issue by adrain1** [mwrlabs/drozer#176]
the info:

![qq 20151120153243](https://cloud.githubusercontent.com/assets/15865347/11294151/20f9e97a-8f9c-11e5-8a4b-230441be2ea2.png)

**Comment by HenryHoggard** [comment]
Can you run drozer in debug mode then post the results.
`drozer console connect --debug`

**Comment by murugant** [comment]
Is this issue solved? I am facing the same issue too in windows.

**Comment by HenryHoggard** [comment]
@murugant In order to debug this issue, we require more information.

Please rerun Drozer in debug mode, this will provide us with more detailed drozer logs.

`$ drozer console connect --debug`

In addition to this, please capture the Android device logs while you run Drozer.

`$ adb logcat -c # clear log`
`$ adb logcat > logfile.txt`

Once you have this information, please attach the log files to this thread and we can assist further.

**Comment by amarekano** [comment]
Hi @murugant @adrain1, please reopen this issue along with the requested logs if you're still having trouble getting drozer working.

We also have a newer version of drozer available that includes multiple bug fixes. We recommend you give it a go and see if it solves your problem.
https://github.com/mwrlabs/drozer/releases/tag/2.4.2
