### ISSUE TITLE
javac: invalid flag: Files\Java\jdk1.6.0_45\bin\javac.exe

### ISSUE THREAD

**Issue by albertKharkov** [mwrlabs/drozer#201]
I got this when I tried to read content provider using drozer

`C:\Program Files\Java\jdk1.6.0_45\bin\javac.exe -cp c:\Program Files\drozer\lib\drozer\lib\android.jar ZipUtil.java
javac: invalid flag: Files\Java\jdk1.6.0_45\bin\javac.exe
Usage: javac <options> <source files>
use -help for a list of possible options
Error whilst compiling the Java sources.`

Could somebody help me with that error?

**Comment by vjex** [comment]
I am also facing the same issue while using scanner module:

`dz> run scanner.provider.finduris -a com.mwr.example.sieve`

**Comment by HenryHoggard** [comment]
In order to debug this issue, we require more information.

Please rerun Drozer in debug mode, this will provide us with more detailed drozer logs.

`$ drozer console connect --debug`

In addition to this, please capture the Android device logs while you run Drozer.

`$ adb logcat -c # clear log`
`$ adb logcat > logfile.txt`

Once you have this information, please attach the log files to this thread and we can assist further.

**Comment by lnterface** [comment]
The java's path cannot have Spaces

**Comment by dinasaif** [comment]
What do you mean by The path cannot have Space?
I also faced this problem 
how can I solve it?

**Comment by amarekano** [comment]
Hi all, this issue has now been resolved with PR #270. This was due to a bug in the way drozer located executables on Windows. Our next drozer release (version 2.4.3) will include this fix. 

If you urgently need to get drozer working, please clone our develop branch and build drozer from source.

Thank you once again for reporting this issue and contributing to improving drozer. :)

**Comment by shashwatpal1021** [comment]
Errors while compiling:
error: invalid flag: -D
Usage: javac <options> <source files>
use --help for a list of possible options
