### ISSUE TITLE
Could not find Java

### ISSUE THREAD

**Issue by Wazza26** [mwrlabs/drozer#257]
Could not find java. Please ensure that it is installed and on your PATH.
If this error persists, specify the path in the ~/.drozer_config file....

I've followed advice posted on other tickets (#198) but had no luck.

```
[executables]
java = C:\Program Files\Java\jdk1.6.0_45\bin
```

**Comment by HenryHoggard** [comment]
Hi @Wazza26  it appears you are missing the `java.exe`

```
[executables]
java = C:\Program Files\Java\jdk1.6.0_45\bin\java.exe
```

**Comment by Wazza26** [comment]
With and without the \bin\java.exe - the error still exists.

**Comment by HenryHoggard** [comment]
In order to debug this issue, we require more information.

Please rerun Drozer in debug mode, this will provide us with more detailed drozer logs.

`$ drozer console connect --debug`

Also please check that the directory you are linking exists.

Once you have this information, please attach the log files to this thread and we can assist further.

**Comment by amarekano** [comment]
Hi @Wazza26, please repoen this issue with the requested information if you're still having trouble getting drozer working on Windows.
